# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('comments', models.IntegerField(null=True, verbose_name='Count comments')),
                ('message', models.CharField(max_length=256, null=True, verbose_name='Message')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='workers.Coin')),
            ],
            options={
                'verbose_name_plural': 'Tweets',
                'verbose_name': 'Tweet',
            },
        ),
    ]
