# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='workers.Coin')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
            },
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='coin',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
