# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_auto_20171219_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetlikes',
            options={'verbose_name': 'Tweets likes', 'verbose_name_plural': 'Tweets likes'},
        ),
    ]
