# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_auto_20171219_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlikes',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets_likes', to='workers.Coin'),
        ),
    ]
