# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_auto_20171219_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlikes',
            name='likes',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Likes'),
        ),
    ]
