# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('parsers', '0005_auto_20171220_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetCountComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_comments', models.IntegerField(blank=True, default=None, null=True, verbose_name='Count comments')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets_comments', to='workers.Coin')),
            ],
            options={
                'verbose_name': 'Count comments',
                'verbose_name_plural': 'Count comments',
            },
        ),
    ]
