# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_tweetcountcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcountcomments',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 12, 37, 1, 165611), null=True, verbose_name='Date update'),
        ),
        migrations.AddField(
            model_name='tweetlikes',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 21, 12, 37, 1, 164868), null=True, verbose_name='Date update'),
        ),
    ]
