# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0007_auto_20171221_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcountcomments',
            name='date_update',
            field=models.DateTimeField(null=True, verbose_name='Date update'),
        ),
        migrations.AlterField(
            model_name='tweetlikes',
            name='date_update',
            field=models.DateTimeField(null=True, verbose_name='Date update'),
        ),
    ]
