# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_auto_20171221_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetcountcomments',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date update'),
        ),
    ]
