# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('parsers', '0009_auto_20171221_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('date_update', models.DateTimeField(blank=True, null=True, verbose_name='Date update')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets_text', to='workers.Coin')),
            ],
            options={
                'verbose_name_plural': 'Tweets text',
                'verbose_name': 'Tweet text',
            },
        ),
    ]
