# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('parsers', '0011_auto_20171221_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_followers', models.TextField(verbose_name='Count followers')),
                ('date', models.DateField(verbose_name='Date')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_followers', to='workers.Coin')),
            ],
            options={
                'verbose_name': 'Twitter followers',
                'verbose_name_plural': 'Twitter followers',
            },
        ),
    ]
