# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0012_twitterfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcountcomments',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='tweetlikes',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='tweettext',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='twitterfollowers',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
