# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0013_auto_20171222_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('count_all', models.IntegerField(null=True, verbose_name='Count of subscribers for all time')),
                ('count_today', models.IntegerField(null=True, verbose_name='Count of subscribers for today')),
            ],
            options={
                'verbose_name_plural': 'Reddit followers',
                'verbose_name': 'Reddit followers',
            },
        ),
    ]
