# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('parsers', '0014_redditfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditfollowers',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reddit_followers', to='workers.Coin'),
        ),
        migrations.AddField(
            model_name='redditfollowers',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
