# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0015_auto_20171222_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterfollowers',
            name='count_followers',
            field=models.IntegerField(verbose_name='Count followers'),
        ),
    ]
