# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0016_auto_20171226_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterfollowers',
            name='count_followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Count followers'),
        ),
    ]
