# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0017_auto_20171226_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('sentence', models.TextField(verbose_name='sentence')),
                ('type', models.CharField(choices=[('Post', 'Post'), ('Repost', 'Repost')], max_length=180, verbose_name='Type')),
                ('negative_value', models.FloatField(verbose_name='Negative_value')),
                ('compound_value', models.FloatField(verbose_name='Compound value')),
                ('neutral_value', models.FloatField(verbose_name='Neutral value')),
                ('positive_value', models.FloatField(verbose_name='Positive value')),
            ],
            options={
                'verbose_name_plural': 'Twitter comments',
                'verbose_name': 'Twitter comment',
            },
        ),
    ]
