# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_statisticparser'),
        ('parsers', '0018_twittercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittercomment',
            name='type',
        ),
        migrations.AddField(
            model_name='twittercomment',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitter_comment_vader', to='workers.Coin'),
        ),
        migrations.AddField(
            model_name='twittercomment',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
