# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_auto_20171227_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittercomment',
            name='compound_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Compound value'),
        ),
        migrations.AlterField(
            model_name='twittercomment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='twittercomment',
            name='negative_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Negative_value'),
        ),
        migrations.AlterField(
            model_name='twittercomment',
            name='neutral_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Neutral value'),
        ),
        migrations.AlterField(
            model_name='twittercomment',
            name='positive_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Positive value'),
        ),
        migrations.AlterField(
            model_name='twittercomment',
            name='sentence',
            field=models.TextField(blank=True, null=True, verbose_name='sentence'),
        ),
    ]
