# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0020_auto_20171227_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittercomment',
            options={'verbose_name': 'Twitter comment vader', 'verbose_name_plural': 'Twitter comments vader'},
        ),
    ]
