# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0021_auto_20171227_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditfollowers',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='twitterfollowers',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
