# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20171229_1227'),
        ('parsers', '0023_marketcapdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github', to='workers.Coin')),
            ],
            options={
                'verbose_name': 'GitHub Data',
                'verbose_name_plural': 'GitHub Data',
            },
        ),
    ]
