# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0024_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='count_rep',
            field=models.IntegerField(null=True, verbose_name='Count of repositories'),
        ),
    ]
