# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0025_github_count_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
