# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0027_auto_20180104_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
