# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0028_auto_20180104_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetcountcomments',
            name='tweet_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID tweet'),
        ),
        migrations.AddField(
            model_name='tweetlikes',
            name='tweet_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID tweet'),
        ),
        migrations.AddField(
            model_name='tweettext',
            name='tweet_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID tweet'),
        ),
    ]
