# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0029_auto_20180209_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercomment',
            name='comment_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID comment'),
        ),
        migrations.AddField(
            model_name='twittercomment',
            name='tweet_id',
            field=models.CharField(max_length=256, null=True, verbose_name='ID tweet'),
        ),
    ]
