# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0031_githubdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubdetails',
            name='commits',
            field=models.IntegerField(null=True, verbose_name='Commits'),
        ),
    ]
