# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0029_coin_github_parser_details_url'),
        ('parsers', '0032_githubdetails_commits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubForks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.IntegerField(null=True, verbose_name='Value')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'verbose_name_plural': 'GitHubForks Data',
                'verbose_name': 'GitHubForks Data',
            },
        ),
        migrations.RemoveField(
            model_name='githubdetails',
            name='coin',
        ),
        migrations.DeleteModel(
            name='GitHubDetails',
        ),
    ]
