# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0029_coin_github_parser_details_url'),
        ('parsers', '0033_auto_20180301_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'verbose_name': 'GitHubStars Data',
                'verbose_name_plural': 'GitHubStars Data',
            },
        ),
        migrations.CreateModel(
            name='GitHubStars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'verbose_name': 'GitHubStars Data',
                'verbose_name_plural': 'GitHubStars Data',
            },
        ),
        migrations.AlterModelOptions(
            name='githubforks',
            options={'verbose_name': 'GitHubStars Data', 'verbose_name_plural': 'GitHubStars Data'},
        ),
        migrations.AlterField(
            model_name='githubforks',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='githubforks',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
