# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0034_auto_20180301_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubcommit',
            name='value',
        ),
        migrations.RemoveField(
            model_name='githubforks',
            name='value',
        ),
        migrations.RemoveField(
            model_name='githubstars',
            name='value',
        ),
    ]
