# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0035_auto_20180301_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubstars',
            name='id_user',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID user '),
        ),
    ]
