# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0036_githubstars_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubstars',
            name='page_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Page number'),
        ),
        migrations.AlterField(
            model_name='githubstars',
            name='id_user',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID user'),
        ),
    ]
