# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0037_auto_20180302_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubforks',
            options={'verbose_name': 'GitHubForks Data', 'verbose_name_plural': 'GitHubForks Data'},
        ),
    ]
