# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0038_auto_20180302_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubforks',
            name='id_fork',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
