# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0039_githubforks_id_fork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubcommit',
            options={'verbose_name': 'GitHubCommit Data', 'verbose_name_plural': 'GitHubCommit Data'},
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='sha',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
