# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0030_auto_20180305_1334'),
        ('parsers', '0040_auto_20180305_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubWatchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('count_watchers', models.IntegerField(blank=True, default=None, null=True, verbose_name='Watchers')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'verbose_name': 'GitHubWatchers Data',
                'verbose_name_plural': 'GitHubWatchers Data',
            },
        ),
    ]
