# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0041_githubwatchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='count_rep',
        ),
        migrations.RemoveField(
            model_name='githubwatchers',
            name='count_watchers',
        ),
        migrations.AddField(
            model_name='github',
            name='repos_id',
            field=models.IntegerField(null=True, verbose_name='ID of repositories'),
        ),
        migrations.AddField(
            model_name='github',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='githubcommit',
            name='github',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.GitHub'),
        ),
        migrations.AddField(
            model_name='githubforks',
            name='github',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.GitHub'),
        ),
        migrations.AddField(
            model_name='githubstars',
            name='github',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.GitHub'),
        ),
        migrations.AddField(
            model_name='githubwatchers',
            name='github',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.GitHub'),
        ),
        migrations.AddField(
            model_name='githubwatchers',
            name='id_watchers',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ID watchers'),
        ),
        migrations.AddField(
            model_name='githubwatchers',
            name='page_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Page number'),
        ),
    ]
