# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0042_auto_20180320_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 12, 7, 48, 843910), verbose_name='date update'),
        ),
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 12, 7, 48, 843748)),
        ),
    ]
