# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0043_auto_20180402_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 9, 49, 10, 701260)),
        ),
        migrations.AlterField(
            model_name='github',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 9, 49, 10, 701424), verbose_name='date update'),
        ),
    ]
