# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0044_auto_20180403_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 8, 12, 28, 883942)),
        ),
        migrations.AlterField(
            model_name='github',
            name='date_update',
            field=models.DateTimeField(null=True, verbose_name='date update'),
        ),
    ]
