# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0045_auto_20180405_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='github',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date update'),
        ),
    ]
