# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('watch_list', 'Watch List Ranking'), ('community_size', 'Community Size Ranking'), ('community_growth', 'Community Growth Ranking'), ('marketcap_size_usd', 'MarketCap Size USD Ranking'), ('marketcap_size_usd_divergence', 'MarketCap Size USD Divergence Ranking'), ('twitter_followers', 'Twitter Followers Ranking'), ('twitter_likes', 'Twitter Likes Ranking'), ('raddit_subscribers', 'Raddit Subscribers Ranking'), ('github_repositary_creations', 'GitHub Repository Creations'), ('vader_twitter_sentiment', 'VADER Twitter Sentiment')], max_length=100)),
                ('total', models.IntegerField()),
                ('overall_day', models.IntegerField()),
                ('overall_week', models.IntegerField()),
                ('overall_month', models.IntegerField()),
                ('overall_three_month', models.IntegerField()),
                ('overall_six_month', models.IntegerField()),
                ('overall_year_month', models.IntegerField()),
                ('trending_day', models.IntegerField()),
                ('trending_week', models.IntegerField()),
                ('trending_month', models.IntegerField()),
                ('trending_three_month', models.IntegerField()),
                ('trending_six_month', models.IntegerField()),
                ('trending_year_month', models.IntegerField()),
                ('growth_day', models.IntegerField()),
                ('growth_week', models.IntegerField()),
                ('growth_month', models.IntegerField()),
                ('growth_three_month', models.IntegerField()),
                ('growth_six_month', models.IntegerField()),
                ('growth_year_month', models.IntegerField()),
            ],
        ),
    ]
