# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20171219_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
