# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
        ('statistic', '0003_auto_20171219_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingstatistic',
            name='coin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.Coin'),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='type',
            field=models.CharField(choices=[('watch_list', 'Watch List Ranking'), ('community_size', 'Community Size Ranking'), ('community_growth', 'Community Growth Ranking'), ('marketcap_size_usd', 'MarketCap Size USD Ranking'), ('marketcap_size_usd_divergence', 'MarketCap Size USD Divergence Ranking'), ('twitter_followers', 'Twitter Followers Ranking'), ('twitter_likes', 'Twitter Likes Ranking'), ('raddit_subscribers', 'Raddit Subscribers Ranking'), ('github_repository_creations', 'GitHub Repository Creations'), ('vader_twitter_sentiment', 'VADER Twitter Sentiment')], max_length=100),
        ),
    ]
