# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0005_auto_20180102_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingstatistic',
            name='type',
            field=models.CharField(choices=[('watch_list', 'Watch List Ranking'), ('community_size', 'Community Size Ranking'), ('community_growth', 'Community Growth Ranking'), ('marketcap_size_usd', 'MarketCap Size USD Ranking'), ('marketcap_size_usd_divergence', 'MarketCap Size USD Divergence Ranking'), ('twitter_followers', 'Twitter Followers Ranking'), ('twitter_likes', 'Twitter Likes Ranking'), ('reddit_subscribers', 'Reddit Subscribers Ranking'), ('github_repository_creations', 'GitHub Repository Creations'), ('vader_twitter_sentiment', 'VADER Twitter Sentiment')], max_length=100),
        ),
    ]
