# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0009_auto_20180313_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='growth_year_month',
            new_name='growth_year',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_day',
            new_name='total_day',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_month',
            new_name='total_month',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_six_month',
            new_name='total_six_month',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_three_month',
            new_name='total_three_month',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_week',
            new_name='total_week',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='overall_year_month',
            new_name='total_year',
        ),
        migrations.RenameField(
            model_name='rankingstatistic',
            old_name='trending_year_month',
            new_name='trending_year',
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='type',
            field=models.CharField(choices=[('watch_list', 'Watch List Ranking'), ('community_size', 'Community Size Ranking'), ('github_total', 'Github Total'), ('marketcap_size_usd_divergence', 'MarketCap Size USD Divergence Ranking'), ('twitter_followers', 'Twitter Followers Ranking'), ('twitter_likes', 'Twitter Likes Ranking'), ('reddit_subscribers', 'Reddit Subscribers Ranking'), ('github_repository_creations', 'GitHub Repository Creations'), ('github_stars', 'Github Repository Stars'), ('github_forks', 'Github Repository Forks'), ('github_commits', 'Github Repository Commits'), ('marketcap_size_usd', 'MarketCap Size USD Ranking'), ('vader_twitter_sentiment', 'VADER Twitter Sentiment')], max_length=100),
        ),
    ]
