# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_auto_20180316_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingstatistic',
            name='growth_day',
        ),
        migrations.RemoveField(
            model_name='rankingstatistic',
            name='total_day',
        ),
        migrations.RemoveField(
            model_name='rankingstatistic',
            name='trending_day',
        ),
    ]
