# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_auto_20180322_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingstatistic',
            name='type',
            field=models.CharField(choices=[('watch_list', 'Watch List Ranking'), ('community_size', 'Community Size Ranking'), ('github_total', 'Github Total'), ('marketcap_size_usd_divergence', 'MarketCap Size USD Divergence Ranking'), ('vader_twitter_sentiment', 'VADER Twitter Sentiment'), ('twitter_followers', 'Twitter Followers Ranking'), ('twitter_likes', 'Twitter Likes Ranking'), ('reddit_subscribers', 'Reddit Subscribers Ranking'), ('github_repository_creations', 'GitHub Repository Creations'), ('github_stars', 'Github Repository Stars'), ('github_forks', 'Github Repository Forks'), ('github_commits', 'Github Repository Commits'), ('marketcap_size_usd', 'MarketCap Size USD Ranking')], max_length=100),
        ),
    ]
