# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0013_auto_20180323_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingstatistic',
            name='growth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='growth_six_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='growth_three_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='growth_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='growth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total_six_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total_three_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='trending_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='trending_six_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='trending_three_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='trending_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingstatistic',
            name='trending_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
