# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20180413_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingstatistic',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
