# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_scrapped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='scrapper',
            field=models.CharField(choices=[('twitter_comments', 'Twitter comments'), ('twitter_likes', 'Twitter likes'), ('twitter_followers', 'Twitter followers'), ('twitter_text', 'Twitter text'), ('reddit_subscribers', 'Reddit subscribers'), ('github_parser', 'Github repository creations number'), ('marketcap_scraper', 'Marketcap Scrapper')], max_length=255),
        ),
    ]
