# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20171218_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(max_length=255, verbose_name='Task ID')),
                ('status', models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('error', 'error')], default='start', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_scrapped_date',
        ),
        migrations.AddField(
            model_name='statisticworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_workers', to='workers.Worker'),
        ),
    ]
