# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20171219_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_calculated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
