# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_statisticparser'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticparser',
            name='is_calculating',
            field=models.BooleanField(default=False),
        ),
    ]
