# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_statisticparser_is_calculating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set([('coin', 'scrapper')]),
        ),
    ]
