# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_auto_20171229_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='scrapper',
            field=models.CharField(choices=[('twitter_comments_vader', 'Twitter comments for vader'), ('twitter_comments', 'Twitter comments'), ('twitter_likes', 'Twitter likes'), ('twitter_followers', 'Twitter followers'), ('twitter_text', 'Twitter text'), ('reddit_subscribers', 'Reddit subscribers'), ('github_parser', 'Github repository creations number'), ('marketcap_scraper', 'Marketcap Scrapper')], max_length=255),
        ),
    ]
