# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_tempgithubrep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempGitHubRep',
            new_name='TempGitHubRating',
        ),
    ]
