# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_temptradingrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTradingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_trend', models.IntegerField()),
                ('six_month_trend', models.IntegerField()),
                ('three_month_trend', models.IntegerField()),
                ('month_trend', models.IntegerField()),
                ('week_trend', models.IntegerField()),
                ('day_trend', models.IntegerField()),
                ('ranking_type', models.CharField(max_length=100)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
        ),
        migrations.RemoveField(
            model_name='temptradingrating',
            name='coin',
        ),
        migrations.DeleteModel(
            name='TempTradingRating',
        ),
    ]
