# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0017_auto_20180110_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='day_trend',
        ),
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='month_trend',
        ),
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='six_month_trend',
        ),
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='three_month_trend',
        ),
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='week_trend',
        ),
        migrations.RemoveField(
            model_name='temptradingvalue',
            name='year_trend',
        ),
        migrations.AddField(
            model_name='temptradingvalue',
            name='time_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temptradingvalue',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
