# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0022_tempwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempGrowthValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time_type', models.CharField(max_length=100)),
                ('ranking_type', models.CharField(max_length=100)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
        ),
    ]
