# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0023_tempgrowthvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='coin',
            name='official_forum',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Official Forum'),
        ),
        migrations.AddField(
            model_name='coin',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='coin',
            name='reddit_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Reddit'),
        ),
        migrations.AddField(
            model_name='coin',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='telegram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='coin',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Website'),
        ),
    ]
