# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0024_auto_20180119_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='btc_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_btc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_usd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='usd_percent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
