# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0025_auto_20180126_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='ranking_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='time_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
