# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0026_auto_20180129_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
