# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0027_auto_20180130_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempValueByPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('time_type', models.CharField(max_length=100, null=True)),
                ('ranking_type', models.CharField(max_length=100, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
        ),
    ]
