# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0028_tempvaluebyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='github_parser_details_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Github parser details'),
        ),
    ]
