# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0029_coin_github_parser_details_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='github_parser_details_url',
        ),
        migrations.AddField(
            model_name='coin',
            name='github_repository_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Github Repository name'),
        ),
    ]
