# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0030_auto_20180305_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='github_repository_name',
        ),
        migrations.AddField(
            model_name='coin',
            name='coinmarketcap_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Coinmarketcap'),
        ),
    ]
