# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0031_tempgithubadditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTotalValueByPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.CharField(max_length=150)),
                ('ranking_type', models.CharField(max_length=100, null=True)),
                ('value', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tempcommunitygrow',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempcommunitygrowthrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempcommunityrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempgithubadditional',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempgithubrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempmarketcapgrow',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempmarketcaprating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempmarketdivergence',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempredditfollowerrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='temptwitterfollowerrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='temptwitterlikes',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempvaderrating',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempvaluebyperiod',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='tempwatchlist',
            name='coin',
        ),
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='time_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temptradingvalue',
            name='ranking_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='temptradingvalue',
            name='time_type',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='TempCommunityGrow',
        ),
        migrations.DeleteModel(
            name='TempCommunityGrowthRating',
        ),
        migrations.DeleteModel(
            name='TempCommunityRating',
        ),
        migrations.DeleteModel(
            name='TempGithubAdditional',
        ),
        migrations.DeleteModel(
            name='TempGitHubRating',
        ),
        migrations.DeleteModel(
            name='TempMarketCapGrow',
        ),
        migrations.DeleteModel(
            name='TempMarketCapRating',
        ),
        migrations.DeleteModel(
            name='TempMarketDivergence',
        ),
        migrations.DeleteModel(
            name='TempRedditFollowerRating',
        ),
        migrations.DeleteModel(
            name='TempTwitterFollowerRating',
        ),
        migrations.DeleteModel(
            name='TempTwitterLikes',
        ),
        migrations.DeleteModel(
            name='TempVaderRating',
        ),
        migrations.DeleteModel(
            name='TempValueByPeriod',
        ),
        migrations.DeleteModel(
            name='TempWatchList',
        ),
    ]
