# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0031_auto_20180323_0851'),
        ('workers', '0031_tempgithubadditional'),
    ]

    operations = [
    ]
