# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0032_auto_20180316_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempgrowthvalues',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temptotalvaluebyperiod',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temptradingvalue',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
