# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0032_merge_20180323_0912'),
        ('workers', '0034_auto_20180322_1137'),
    ]

    operations = [
    ]
