# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0035_merge_20180323_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='parsing_day',
            field=models.IntegerField(null=True),
        ),
    ]
