# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0036_coin_parsing_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticScrappers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('scrapper', models.CharField(max_length=120, verbose_name='Scrapper')),
                ('task_id', models.CharField(max_length=255, verbose_name='Task ID')),
                ('status', models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('error', 'error')], default='start', max_length=50)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Coin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StatisticParser',
        ),
        migrations.RemoveField(
            model_name='statisticworker',
            name='worker',
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='coin',
        ),
        migrations.DeleteModel(
            name='StatisticWorker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
