# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0037_auto_20180326_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatisticScrappers',
            new_name='StatisticScrapper',
        ),
    ]
