# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0038_auto_20180326_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ['title']},
        ),
    ]
